### PR TITLE
Enable bubbling for DOM3 Event

### PR DESCRIPTION
**Pull request by cherniavskii**
https://developer.mozilla.org/en-US/docs/Web/API/Event/Event

### CODE REVIEW

**Comment by tmcw** [comment]
Should this be a default, or optional? I would guess that at least some users want non-bubbling events.

**Comment by cherniavskii** [comment]
I thought about that, but since bubbling is enabled by default [here](https://github.com/tmcw/happen/blob/master/happen.js#L47) and [here](https://github.com/tmcw/happen/blob/master/happen.js#L90), I left it default too.
Probably nice to have it configurable, I can submit new PR with such feature :)

**Comment by cherniavskii** [comment]
@tmcw should I change something in this PR?

**Comment by cherniavskii** [comment]
@tmcw Thanks!
Any chances you will publish new version to NPM soon?

**Comment by tmcw** [comment]
Yep, it's on my todo list for this evening.

**Comment by cherniavskii** [comment]
Great, thanks! :)

**Comment by tmcw** [comment]
Published as 0.3.2!

**Pull request merged**
